# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jw29ZgBe_jI0JjcHzG5HTEzDOHLz5Iq-
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("sales_data (1).csv")

# Total Sales
total_sales = df["Total_Sales"].sum()
print("\nTotal Sales:", total_sales)

sales_by_product = df.groupby("Product")["Total_Sales"].sum()
print("\nSales by Product:")
print(sales_by_product)

sales_by_region = df.groupby("Region")["Total_Sales"].sum()
print("\nSales by Region:")
print(sales_by_region)

plt.figure(figsize=(8,5))

sales_by_product.plot(kind="bar", color="skyblue")

plt.title("Total Sales by Product")
plt.xlabel("Product")
plt.ylabel("Total Sales")
plt.xticks(rotation=45)

plt.tight_layout()
plt.savefig("bar_chart.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(6,6))

sales_by_region.plot(
    kind="pie",
    autopct="%1.1f%%"
)

plt.title("Sales Distribution by Region")
plt.ylabel("")

plt.tight_layout()
plt.savefig("pie_chart.png", dpi=300, bbox_inches="tight")
plt.show()

df["Date"] = pd.to_datetime(df["Date"])

daily_sales = df.groupby("Date")["Total_Sales"].sum()

plt.figure(figsize=(10,5))

daily_sales.plot(marker="o")

plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Total Sales")

plt.grid(True)

plt.tight_layout()
plt.savefig("line_chart.png", dpi=300, bbox_inches="tight")
plt.show()

print("========== PROJECT INSIGHTS ==========")

print("Total Revenue :", total_sales)
print("Highest Selling Product :", sales_by_product.idxmax())
print("Best Performing Region :", sales_by_region.idxmax())
print("Average Sales :", round(df["Total_Sales"].mean(), 2))

print("======================================")

from google.colab import files

files.download("bar_chart.png")
files.download("pie_chart.png")
files.download("line_chart.png")